### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by fjandrad** [diegoferigo/devenv#5]
# Problem description
Tried in Ubuntu 18.04.4 
Trying to run the example and seems fine until `devenv -f devenv.yml -o devenv-docker-compose.yml up`  where  I get 

```
Traceback (most recent call last):
  File "/home/pako/.local/bin/devenv", line 11, in <module>
    load_entry_point('devenv==1.0', 'console_scripts', 'devenv')()
  File "/home/pako/.local/lib/python3.6/site-packages/devenv/__main__.py", line 39, in main
    from compose.cli.main import main as compose_main
ModuleNotFoundError: No module named 'compose'
```

Googling the error it seems like I'm missing docker-compose. I thought installing it would help.

But it seems it was installed from snap whith this version

```
which docker-compose
/snap/bin/docker-compose

docker-compose --version
docker-compose version 1.23.2, build unknown
```

## Troubleshooting installation

Running the pip3 installation I get:

```
Successfully installed PyYAML-3.13 certifi-2020.4.5.1 chardet-3.0.4 devenv-1.0 docker-3.7.3 docker-pycreds-0.4.0 idna-2.7 requests-2.20.1 six-1.15.0 urllib3-1.24.3 websocket-client-0.57.0
```

I do not see any docker-compose mentions as installed. I see a docker 3.7.3 being installed

I had previously installed docker for something else ans this is what I get from docker version

`Docker version 19.03.8, build afacb8b7f0`

Tried to run directly the docker compose command and got

```
docker-compose -f devenv-docker-compose.yml up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```

So not sure what could be the problem

**Comment by fjandrad** [comment]
As suggested I did:
```
pip3 install docker-compose
```

Now when running the example I get:
```
Executing docker-compose
Pulling example (devenv_example:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling example (devenv_example:)...
ERROR: pull access denied for devenv_example, repository does not exist or may require 'docker login'
```

So I guess it is running is just a matter of the image now.

**Comment by fjandrad** [comment]
Looking at `setup.py` in detail I saw:
```
install_requires=[
    'docker<4.0',
    'PyYAML<=4.3',
    'requests<2.21'
    'docker-compose',
  ],
```

I think there is a `,` missing after  `'requests<2.21'`

**Comment by diegoferigo** [comment]
> from compose.cli.main import main as compose_main

Yep it seems that your system either does not have or does not find the `docker-compose` python package. How did you install it? Can you post the full output of the `pip` command and your environment (from `env`)? When you install `devenv`, `docker-compose` should be automatically downloaded since it's one of its dependencies.

> I do not see any docker-compose mentions as installed.

I suspect that it finds it already installed somewhere else in the system, not sure where and from which repo package.

**Comment by fjandrad** [comment]
The problem (besides missing docker-compose) was that even if docker was installed with ppa there was also an installation done with snap that somehow was having priority and creating issues as described in [here](https://github.com/docker/for-linux/issues/1009). Removing snap installation allowed to make it work.
